version: '3'
services:
  application:
    container_name: demo-app
    build: ../../../
    ports:
      - "8080:8080"
      - "5050:5050"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      DB_HOST: db
      DEBUG_PORT: "*:5050"
    depends_on:
      - postgres
  postgres:
    container_name: demo-db
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      TZ: "Europe/Moscow"
    ports:
      - "5432:5432"